# WQD7005 - Data Mining
## Online assessment

#### Matrix Number : 17201091/1 

#### Name                 : LIU,HONGYANG

#### Cleaning data

In [1]:
#importing libraries
import csv
import pandas as pd

In [2]:
#Importing all csv
oilCrawl = pd.read_csv("cleanOilRate.csv")

#Viewing oilCrawl
oilCrawl.head()

   Year  Price(USD)  Open(USD)  High(USD)  Low(USD)  Close(USD)  Change %
0  2020       50.73      61.18      63.27     28.93       28.93    -52.62
1  2019       57.05      46.54      66.30     46.54       61.06     34.46
2  2018       64.90      60.37      76.41     42.53       45.41    -24.84
3  2017       50.84      52.33      60.42     42.53       60.42     12.47
4  2016       43.58      36.76      54.06     26.21       53.72     45.03

In [3]:
# check Nan data
oilCrawl.isnull().sum()

Year          0
Price(USD)    0
Open(USD)     0
High(USD)     0
Low(USD)      0
Close(USD)    0
Change %      0
dtype: int64

##### the result above showed it's clean!

In [4]:
#show the exact info
oilCrawl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 7 columns):
Year          34 non-null int64
Price(USD)    34 non-null float64
Open(USD)     34 non-null float64
High(USD)     34 non-null float64
Low(USD)      34 non-null float64
Close(USD)    34 non-null float64
Change %      34 non-null float64
dtypes: float64(6), int64(1)
memory usage: 1.9 KB

In [5]:
# pandas melt to reshape data frame
pd.melt(oilCrawl,id_vars=['Year','Price(USD)','Change %'])

     Year  Price(USD)  Change %    variable   value
0    2020       50.73    -52.62   Open(USD)   61.18
1    2019       57.05     34.46   Open(USD)   46.54
2    2018       64.90    -24.84   Open(USD)   60.37
3    2017       50.84     12.47   Open(USD)   52.33
4    2016       43.58     45.03   Open(USD)   36.76
5    2015       48.72    -30.70   Open(USD)   52.72
6    2014       93.17    -45.55   Open(USD)   95.14
7    2013       97.98      6.90   Open(USD)   93.14
8    2012       94.05     -7.08   Open(USD)  102.96
9    2011       94.88      8.15   Open(USD)   91.59
10   2010       79.48     15.10   Open(USD)   81.52
11   2009       61.95     78.00   Open(USD)   46.17
12   2008       99.67    -53.52   Open(USD)   99.64
13   2007       72.34     57.68   Open(USD)   60.77
14   2006       66.05     -0.34   Open(USD)   63.11
15   2005       56.64     40.82   Open(USD)   42.16
16   2004       41.51     33.37   Open(USD)   33.71
17   2003       31.08      4.17   Open(USD)   31.97
18   2002       26.19     56.36   Open(USD)   21.13
19   2001       25.98    -25.30   Open(USD)   27.29
20   2000       30.38      3.73   Open(USD)   25.56
21   1999       19.35    112.19   Open(USD)   12.42
22   1998       14.42    -31.22   Open(USD)   17.41
23   1997       20.61    -31.85   Open(USD)   25.55
24   1996       22.12     32.55   Open(USD)   19.83
25   1995       18.43      9.96   Open(USD)   17.45
26   1994       17.20     25.23   Open(USD)   14.52
27   1993       18.43    -27.19   Open(USD)   19.03
28   1992       20.58      1.78   Open(USD)   19.43
29   1991       21.54    -32.76   Open(USD)   26.53
..    ...         ...       ...         ...     ...
106  2016       43.58     45.03  Close(USD)   53.72
107  2015       48.72    -30.70  Close(USD)   37.04
108  2014       93.17    -45.55  Close(USD)   53.45
109  2013       97.98      6.90  Close(USD)   98.17
110  2012       94.05     -7.08  Close(USD)   91.83
111  2011       94.88      8.15  Close(USD)   98.83
112  2010       79.48     15.10  Close(USD)   91.38
113  2009       61.95     78.00  Close(USD)   79.39
114  2008       99.67    -53.52  Close(USD)   44.60
115  2007       72.34     57.68  Close(USD)   95.95
116  2006       66.05     -0.34  Close(USD)   60.85
117  2005       56.64     40.82  Close(USD)   61.06
118  2004       41.51     33.37  Close(USD)   43.36
119  2003       31.08      4.17  Close(USD)   32.51
120  2002       26.19     56.36  Close(USD)   31.21
121  2001       25.98    -25.30  Close(USD)   19.96
122  2000       30.38      3.73  Close(USD)   26.72
123  1999       19.35    112.19  Close(USD)   25.76
124  1998       14.42    -31.22  Close(USD)   12.14
125  1997       20.61    -31.85  Close(USD)   17.65
126  1996       22.12     32.55  Close(USD)   25.90
127  1995       18.43      9.96  Close(USD)   19.54
128  1994       17.20     25.23  Close(USD)   17.77
129  1993       18.43    -27.19  Close(USD)   14.19
130  1992       20.58      1.78  Close(USD)   19.49
131  1991       21.54    -32.76  Close(USD)   19.15
132  1990       24.53     30.40  Close(USD)   28.48
133  1989       19.64     27.57  Close(USD)   21.84
134  1988       15.97      2.27  Close(USD)   17.12
135  1987       19.20     -6.64  Close(USD)   16.74

[136 rows x 5 columns]

In [10]:
# pandas pivot_table
pd.pivot_table(,index=['Year'])

NameError: name 'df' is not defined

In [7]:
#Exporting new csv after data are cleaned
oilCrawl.to_csv('cleanCurrencyExchange.csv',mode = 'w', index=False)